development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: activeportal_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: activeportal_test
  pool: 5
  username: postgres
  password:
